export const gimnospermas = {
  "Graellsia isabellae": "Mariposa isabelina",
  "Noctua pronuba": "Gusano gris",
  "Lasiocampa quercus": "Mariposa del roble",
  "Saturnia pyri": "Gran pavón nocturno",
  "Acherontia atropos": "Esfinge de la calavera",
  "Macroglossum stellatarum": "Mariposa colibrí",
  "Colias crocea": "Colias común",
  "Gonepteryx rhamni": "Limonera",
  "Pieris rapae": "Blanquita de la col",
  "Tipula maxima": "Mosquito gigante",
  "Lucilia caesar": "Mosca verde",
  "Calliphora vomitoria": "Mosca de la botella azul",
  "Scolia flavifrons": "Avispa de alas azules",
  "Formica rufa": "Hormiga roja de la madera",
  "Vespula vulgaris": "Avispa común",
  "Xylocopa violacea": "Abejorro carpintero",
  "Bombus lucorum": "Abejorro blanco",
  "Cicindela campestris": "Escarabajo tigre verde",
  "Lucanus cervus": "Ciervo volante",
  "Dorcus parallelopipedus": "Ciervo volante menor",
  "Geotrupes stercorarius": "Escarabajo estercolero",
  "Capris lunaris": "",
  "Oryctes nasicornis": "Escarabajo rinoceronte europeo",
  "Cetonia aurata": "Escarabajo de las rosas",
  "Melolontha melolontha": "Escarabajo de mayo",
};
